[package]
name = "day16"
version = "0.1.0"
authors = ["geb"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main_benchmark"
harness = false